services:
  mbl:
    image: tanlin2013/mbl:latest
    pull_policy: always
    shm_size: 10.24gb
    ports:
      - "8265:8265"
    networks:
      - minio_frontend
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
#      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
#      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
#      - MLFLOW_TRACKING_TOKEN=${MLFLOW_TRACKING_TOKEN}
    volumes:
      - ~/projects/mbl/scripts:/home/mbl/scripts
      - ~/.aws:/root/.aws
      - ray:/root/ray_results
    entrypoint: python
    command: scripts/sampler.py

volumes:
  ray:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/TaoLin_shared/docker/volumes/ray_results/_data

networks:
    minio_frontend:
        external: true
