[tool.poetry]
name = "mbl"
version = "0.1.1"
description = "Many-body localization"
authors = ["taolin <tanlin2013@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
tqdm = "^4.63.0"
PyYAML = "^6.0"
numpy = "1.21.6"
pandas = "1.4.2"
pandera = "0.10.1"
awswrangler = "2.15.1"
validators = "^0.19.0"
tnpy = { version = "0.1.1a2", optional = true }
apache-airflow = { version = "2.2.5", optional = true }
mlflow = { version = "1.25.1", optional = true }
ray = { version = "1.12.0", optional = true }
dask = { version = "2022.4.1", optional = true }
dask-jobqueue = { version = "0.7.3", optional = true }
streamlit = { version = "1.8.1", optional = true }
orjson = { version = "3.6.8", optional = true }
plotly = { version = "5.7.0", optional = true }

[tool.poetry.extras]
tnpy = ["tnpy"]
mlops = ["apache-airflow", "mlflow"]
distributed = ["ray", "dask", "dask-jobqueue"]
dashboard = ["streamlit", "orjson", "plotly"]

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"
pylint = "^2.13.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
