[tool.poetry]
name = "mbl"
version = "0.2.0a2"
description = "Many-body localization"
authors = ["taolin <tanlin2013@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
tqdm = "^4.63.0"
PyYAML = "^6.0"
numpy = "1.21.6"
pandas = "1.4.2"
pandera = "0.11.0"
awswrangler = "2.15.1"
validators = "^0.19.0"
pysftp = "^0.2.9"
tnpy = { version = "0.1.1a2", optional = true }
apache-airflow = { version = "2.3.2", optional = true }
mlflow = { version = "1.25.1", optional = true }
protobuf = { version = "3.20.1", optional = true }
ray = {extras = ["default", "tune"], version = "1.12.1", optional = true }
tensorboard = { version= "2.9.0", optional = true }
dask = { version = "2022.5.2", optional = true }
dask-jobqueue = { version = "0.7.3", optional = true }
streamlit = { version = "1.10.0", optional = true }
orjson = { version = "3.7.1", optional = true }
plotly = { version = "5.8.0", optional = true }
pandas-profiling = { version = "3.1.0", optional = true }

[tool.poetry.extras]
tnpy = ["tnpy"]
mlops = ["apache-airflow", "mlflow"]
distributed = ["protobuf", "ray", "tensorboard", "dask", "dask-jobqueue"]
dashboard = ["streamlit", "orjson", "plotly", "pandas-profiling"]

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"
pylint = "^2.13.7"
jupyter = "^1.0.0"
moto = "^3.1.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
