system_size:
  - 8
  - 10
  - 12
  - 14
  - 16
  - 18
  - 20
disorder:
  - 0.5
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  - 10.0
truncation_dim:
  - 8
  - 16
  - 32
  - 64
seed:
  start: 2000
  end: 2200
  step: 1
overall_const:
  - 1
penalty:
  - 0
s_target:
  - 0
offset:
  - 0
relative_offset:
  - 0.1
  - 0.5
  - 0.9
method:
  - min
  - max
