name: cdk-deploy

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'cdk command (eg. `deploy` or `destroy`)'
        type: choice
        required: true
        options:
          - deploy
          - destroy
      stack:
        description: 'cdk stack (name of stack or `--all`)'
        required: true
        default: '--all'
      args:
        description: 'cdk args (eg. `--force` or `--require-approval never`)'
        required: true
        default: '--require-approval never'

permissions:
  id-token: write
  contents: read

jobs:
  cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/setup-node@v2
        with:
          node-version: "17.9.0"
      -
        name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      -
        name: Deploy stack
        run: |
          cd mlflow-tracker/aws
          yarn
          yarn cdk ${{ github.event.inputs.command }} \
                    ${{ github.event.inputs.stack }} \
                    ${{ github.event.inputs.args }}
