name: cdk_deploy

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'cdk command (eg. deploy or destroy)'
        required: true
        default: 'deploy'
      args:
        description: 'cdk args'
        required: true
        default: '--all --require-approval never'

jobs:
  cdk:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Run cdk command
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: github.event.inputs.command
          cdk_stack: '*'
          cdk_args: github.event.inputs.args
          actions_comment: false
          working_dir: 'devops/mlflow/'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
