name: CI deploy

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Working machine'
        required: true
        default: 'workstation'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo target
        run: echo "Deploying to targeted machine - ${{ github.event.inputs.target }}"

      - name: Deploy to workstation through ssh
        if: github.event.inputs.target == 'workstation'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WORKSTATION_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            nohup \
            docker run --entrypoint python --rm --pull=always \
            -v ~/data:/home/mbl/data tanlin2013/mbl scripts/sampler.py \
            > foo.out 2> foo.err < /dev/null &

      - name: rsync deployments
        if: github.event.inputs.target == 'cluster'
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          remote_path: '~/projects/'
          remote_host: ${{ secrets.CLUSTER_HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}

      - name: Deploy to cluster through ssh
        if: github.event.inputs.target == 'cluster'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLUSTER_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            singularity build --fakeroot mbl.sif singularity.def &&
            singularity exec --bind ~/data:/data mbl.sif python scripts/sampler.py
