name: job-deploy

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy'
        type: choice
        required: true
        default: 'minio'
        options:
          - minio
          - sftp
      docker_compose_cmd:
        description: 'Run docker compose command'
        type: choice
        required: false
        default: 'up -d'
        options:
          - up -d
          - down

jobs:
  deploy-service:
    name: Deploy service on workstation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo service
        run: echo "Deploying the service - ${{ github.event.inputs.service }}"

      - name: Rsync repo to workstation
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          remote_path: '~/projects/mbl'
          remote_host: ${{ secrets.WORKSTATION_HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}

      - name: Deploy minio mlflow server on workstation
        if: github.event.inputs.service == 'minio'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WORKSTATION_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd projects/mbl/mlflow-tracker/minio &&
            docker compose ${{ github.event.inputs.docker_compose_cmd }}

      - name: Deploy sftp server on workstation
        if: github.event.inputs.service == 'sftp'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WORKSTATION_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd projects/mbl/mlflow-tracker/aws/sftp &&
            docker compose ${{ github.event.inputs.docker_compose_cmd }}
