name: Test

on:
  workflow_run:
    workflows: ["Docker build"]
    types:
      - completed

jobs:
  in-docker:
    runs-on: ubuntu-latest
    container:
      image: docker://${{ github.repository }}:sha-${{ github.sha }}
      options: --shm-size=3gb
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.KEY }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dev dependencies
        run: |
          poetry install --all-extras

      - name: Test
        run: |
          poetry run pytest tests/ -s --cov=${{ github.event.repository.name }}/ --cov-report=term-missing ${@-}
          poetry run coverage xml

      - name: Report Coverage
        uses: codecov/codecov-action@v3
